import ProductHeader from "@/Components/ProductHeader";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Task 4 | Products",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-black antialiased`}>
      <ProductHeader />
        {children}
      </body>
    </html>
  );
}
